---
# tasks file for docker

- name: update cache
  apt: 
    update_cache: yes

- name: install packages 
  apt: 
    name: '{{ item }}'
  with_items:
    - apt-transport-https 
    - ca-certificates
    - curl 
    - gnupg2 
    - software-properties-common


 
- name: ajout clef Docker
  apt_key: 
    url: https://download.docker.com/linux/debian/gpg
  when: ansible_lsb['id']|lower == 'debian'

- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
  when: ansible_lsb['id']|lower == 'debian'

- name: ajout clef Docker
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_lsb['id']|lower == 'ubuntu'

- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_lsb['id']|lower == 'ubuntu'


- name:    Install Docker
  apt: name=docker-ce
